baseurl = "https://blog.scottic.us/"
languageCode = "en-us"
title = "blog.scottic.us"
theme = "terminal"
paginate = 5

[params]
    twitter = "scotty"
    github = "sasimpson"
    keybase = "sasimpson"
    disqus = "scotticus"
    author = "scott"
    avatar = "https://s.gravatar.com/avatar/e633bf55b82efbc02e5a85b53c61afea?s=80"
    themeColor = "green"
    fullWidthTheme = false
    centerTheme = true

[languages]
    [languages.en]
        title = "hi."
        subtitle = "my blog."
        [languages.en.menu]
            [[languages.en.menu.main]]
                identifier = "about"
                name = "about"
                url = "/about"
            [[languages.en.menu.main]]
                identifier = "resume"
                name = "resume"
                url = "/resume"