version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: ssimpson/hugo:latest

    steps:
      # get the code
      - checkout

      # update the theme submodule
      - run: git submodule update --init themes/terminal
      # - run: git submodule update --recursive --remote

      - run: hugo version
      #run hugo to generate with theme
      - run: hugo -t terminal

      #upload artifacts for next job step
      # - store_artifacts:
      #     path: /root/project/public

      - persist_to_workspace:
          root: /root
          paths:
          - project/public
  
  deploy:
    docker:
      - image: google/cloud-sdk
    
    steps:
      - attach_workspace:
          at: /tmp/project

      - run: ls -l /tmp/project
      
      # - run: | 
      #     echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
      #     gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      #     gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      # - run: gsutil -m cp -r public/* gs://blog.scottic.us/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy