version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: ssimpson/hugo:latest

    steps:
      # get the code
      - checkout

      # update the theme submodule
      - run: git submodule update --recursive --remote

      #run hugo to generate with theme
      - run: hugo -t terminal

      #upload artifacts for next job step
      - store_artifacts:
          path: /root/project/public  